#!/bin/bash
#----------------------------------------------------------------------------
# Creates a LaTeX file based on template.tex for a given set of parameters.
#----------------------------------------------------------------------------

VERSION=0.1
USAGE="Usage: create_homework -q [quarter dir] -c [class] -d [directory name] -t [hw title] -n [problem count]"

if [ $# == 0 ] ; then
    echo $USAGE
    exit 1;
fi

# Options processing --------------------------------------------------------

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -q)
    QTR=$2
    shift       # shift past the argument
    shift       # shift past the value
    ;;
    -c)
    CLASS=$2
    shift
    shift
    ;;
    -d)
    HWDIR=$2
    shift
    shift
    ;;
    -t)
    TITLE=$2
    shift
    shift
    ;;
    -n)
    NUMPROBS=$2
    shift
    shift
    ;;
    *)
    echo "I do not recognize $1"
    exit 1
    ;;
esac
done

if [ ! -d $QTR/$CLASS ]; then
    echo "Error: $CLASS directory does not exist. Please create it first"
    exit 1;
fi

if [ -d $QTR/$CLASS/$HWDIR ]; then
    echo "Error: directory $CLASS/$HWDIR already exists! Please specify a new directory"
    exit 1;
fi
 
#debugging   
echo "Quarter $QTR Class $CLASS title $TITLE num $NUMPROBS"

# creating the directory -----------------------------------------------------

mkdir $QTR/$CLASS/$HWDIR

# copy template in -----------------------------------------------------------

cp template.tex $QTR/$CLASS/$HWDIR/$HWDIR.tex

# modify the template with the specified parameters --------------------------

sed -i "s/<<CLASS>>/$CLASS/g" $QTR/$CLASS/$HWDIR/$HWDIR.tex
sed -i "s/<<TITLE>>/$TITLE/g" $QTR/$CLASS/$HWDIR/$HWDIR.tex

# build the problem template string ------------------------------------------

for i in {1..$NUMPROBS}; do
    cat problem-template.tex >> $QTR/$CLASS/$HWDIR/$HWDIR.tex
done


echo "\end{document}" >> $QTR/$CLASS/$HWDIR/$HWDIR.tex
